### PR TITLE
Turbo mega prompt

### PR DESCRIPTION
**Pull request by jwehrmann**

### CODE REVIEW

**Comment by joaovbsevero** [comment]
wingman:summarize

**Comment by joaovbsevero** [comment]
## Breaking changes:

1. `PromptEnsemble` class:
   - Constructor now expects `templates` to be a list of strings only.
   - Constructor argument `prompt_class` now expects a `Type[DynamicPrompt]`.
2. `TurboPrompt` class:
   - Constructor arguments `system_prompt`, `user_prompt`, and `assistant_prompt` are replaced with `system_templates`, `user_templates`, and `assistant_templates`.
   - Constructor argument `title` is removed.
   - `add_user_template`, `add_system_template`, and `add_assistant_template` methods now expect a `template_name` argument.
   - `add_user_message`, `add_system_message`, and `add_assistant_message` methods now expect a `template_name` argument.
   - `from_file` class method updated.
   - `to_dynamic` method updated.
4. `DynamicPrompt` class:
   - Constructor arguments `prompt`, `settings`, and `title` are replaced with `template`, `name`, `description`, and `settings`.
   - Constructor argument `template_vars` is now optional.
7. `prompt_builder.py` file removed.
8. `BasePrompt` and `Prompt` classes removed.

**Comment by silvianunes** [comment]
## Breaking Changes:
1. Removal of `prompt_builder.py` and refactoring of `DynamicPrompt`
    - The `prompt_builder.py` file has been removed, and the `DynamicPrompt` class has been moved to the `dynamic.py` file.
    - **Affected elements:** Any code that imports `DynamicPrompt` or other classes from `prompt_builder.py` should be updated to import from `dynamic.py` instead.
    - The changes can be seen [here](https://github.com/TeiaLabs/prompts/pull/15/files#diff-f7e1c4b0c03151c6b7725c21e85e7cc4265bfe3d5162fa1a1c5abdc732bbc61b).

2. Changes in `PromptEnsemble` constructor and method signatures
    - The constructor of `PromptEnsemble` now takes `templates` and `expected_vars` as arguments instead of `templates`, `expected_vars`, and `prompt_class`.
    - The `add_user_template`, `add_system_template`, and `add_assistant_template` methods now take `template_name` and `template` as arguments instead of `prompt_name` and `template`.
    - **Affected elements:** Any code that uses the `PromptEnsemble` class and its methods should be updated to match the new signatures.
    - The changes can be seen [here](https://github.com/TeiaLabs/prompts/pull/15/files#diff-cbc7a62fa1aad40c8ca9d5f87ea9f34662789afded12532eaf7e4fa5d1ba67a9).

3. Changes in `TurboPrompt` constructor and method signatures
    - The constructor of `TurboPrompt` now takes `system_templates`, `user_templates`, and `assistant_templates` as arguments instead of `system_prompt`, `user_prompt`, and `assistant_prompt`.
    - The `add_user_message`, `add_system_message`, and `add_assistant_message` methods now take `template_name` as an additional argument.
    - **Affected elements:** Any code that uses the `TurboPrompt` class and its methods should be updated to match the new signatures.
    - The changes can be seen [here](https://github.com/TeiaLabs/prompts/pull/15/files#diff-8926d5a668959ad1b37b42b99b4c88a3803c89581b5a2bf5fccd8e5df24fe52d).

**Comment by silvianunes** [comment]
## :star: New Features
1. Added support for OpenAI name
- The system now supports the OpenAI name feature, allowing for more precise identification and categorization of AI models.

2. Introduced generic add_template and add_initial_template_data methods
- These new methods allow for more flexible and dynamic addition of templates and initial template data, enhancing the system's adaptability to different project requirements.

## :wrench: Changes to existing features
1. Renamed prompt to template in DynamicPrompt
- This change was made to better reflect the functionality of the feature and to align with OpenAI terminology.

2. Updated ensemble prompt with new DynamicCode
- The ensemble prompt has been updated to work seamlessly with the newly introduced DynamicCode, ensuring consistency across the system.

3. Renamed files and classes for better organization
- Several files and classes have been renamed to improve the system's structure and readability.

4. Adjusted tests to evaluate name
- Tests have been updated to evaluate the new name feature, ensuring its correct functionality.

## :beetle: Bug Fixes
1. Fixed requirements
- The project's requirements have been updated to ensure the correct operation of all features.

2. Fixed indentation and formatting issues
- Several indentation and formatting issues have been corrected, improving the readability and maintainability of the code.

3. Fixed backwards compatibility in dynamic prompt
- Backwards compatibility issues in the dynamic prompt feature have been addressed, ensuring the system works correctly with older versions.

4. Fixed imports of renamed files
- Imports have been updated to reflect the renaming of several files, ensuring the correct operation of all features.

**Pull request merged**
